### ISSUE TITLE
Arrow keys produce weird results for multiline inputs

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#78]
Reproduce:
* https://insect.sh/
* Enter "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
* Press left arrow a few times

**Comment by sharkdp** [comment]
@jcubic Your help would be very appreciated here... only if you are interested and have time to look into this, of course. Do you think this is related to jquery.terminal or am I using it incorrectly?

**Comment by jcubic** [comment]
I can only see that the last line jumps by few pixels while you move the cursor but this one I've fixed, you can see on http://terminal.jcubic.pl/#demo . Is it something else? if yes that what and what browser/os?

**Comment by jcubic** [comment]
Oh, I've see this in reference issue. But I can't reproduce this on Chromium/Linux. the site is working fine. Also you have old version of jQuery Terminal.

**Comment by sharkdp** [comment]
I just realized that this only happens if the browser window is smaller than full size (such that the terminal part has to be resized to smaller sizes). I'm using Chrome/Linux.

> I can only see that the last line jumps by few pixels while you move the cursor but this one I've fixed

Cool. Will upgrade jQuery Terminal soon.

**Comment by jcubic** [comment]
yes, there is issue when you resize on your site, try latest version, if you'll still have issues I can take a look.

**Comment by sharkdp** [comment]
@jcubic Thanks! I've updated to jQuery Terminal 1.4.3 and the issue still appears. Note that I have made some changes to `jquery.terminal-1.4.3.css` (`terminal.css`), but the same issue appears with the original stylesheet.

**Comment by jcubic** [comment]
Ok, found the reason, the problem is your prompt. When calculating size of the command line first line it count how many characters the prompt have and in your case with unicode prompt is count it as 2 characters (`≫` and space) and your character you've pick is larger then the monospace letter.

If you change the prompt with `>>` it will work.

I think that I can fix your case by calculating number of characters prompt occupy by not using length, but using `Math.ceil(width / letter_width)`. but it will also don't work when user type unicode characters that are larger.

**Comment by sharkdp** [comment]
Ah, I see. Good catch! Thank you very much for looking into this.

I found out that the issue is gone if the `≫` character is not rendered in a bold font. Maybe I can find some CSS workaround.

**Comment by sharkdp** [comment]
> I found out that the issue is gone if the ≫ character is not rendered in a bold font. Maybe I can find some CSS workaround.

Oh, no. that's not actually true.

**Comment by sharkdp** [comment]
Fixed with a small hack:

```js
prompt: "[[;;;prompt]&#8811; ]"
```

``` css
/* jQuery Terminal */
.prompt {
    font-weight: bold;
    /* workaround for https://github.com/sharkdp/insect/issues/78 */
    letter-spacing: 0.1px;
}
```
